// Code generated by go-swagger; DO NOT EDIT.

package personnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPersonnelSearchHandlerFunc turns a function with the right signature into a get personnel search handler
type GetPersonnelSearchHandlerFunc func(GetPersonnelSearchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPersonnelSearchHandlerFunc) Handle(params GetPersonnelSearchParams) middleware.Responder {
	return fn(params)
}

// GetPersonnelSearchHandler interface for that can handle valid get personnel search params
type GetPersonnelSearchHandler interface {
	Handle(GetPersonnelSearchParams) middleware.Responder
}

// NewGetPersonnelSearch creates a new http.Handler for the get personnel search operation
func NewGetPersonnelSearch(ctx *middleware.Context, handler GetPersonnelSearchHandler) *GetPersonnelSearch {
	return &GetPersonnelSearch{Context: ctx, Handler: handler}
}

/*
	GetPersonnelSearch swagger:route GET /personnel/search personnel getPersonnelSearch

Searches for people
*/
type GetPersonnelSearch struct {
	Context *middleware.Context
	Handler GetPersonnelSearchHandler
}

func (o *GetPersonnelSearch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPersonnelSearchParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
