// Code generated by go-swagger; DO NOT EDIT.

package personnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMeDetailsHandlerFunc turns a function with the right signature into a get me details handler
type GetMeDetailsHandlerFunc func(GetMeDetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeDetailsHandlerFunc) Handle(params GetMeDetailsParams) middleware.Responder {
	return fn(params)
}

// GetMeDetailsHandler interface for that can handle valid get me details params
type GetMeDetailsHandler interface {
	Handle(GetMeDetailsParams) middleware.Responder
}

// NewGetMeDetails creates a new http.Handler for the get me details operation
func NewGetMeDetails(ctx *middleware.Context, handler GetMeDetailsHandler) *GetMeDetails {
	return &GetMeDetails{Context: ctx, Handler: handler}
}

/*
	GetMeDetails swagger:route GET /me/details personnel getMeDetails

Full details about logged in user
*/
type GetMeDetails struct {
	Context *middleware.Context
	Handler GetMeDetailsHandler
}

func (o *GetMeDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMeDetailsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
