// Code generated by go-swagger; DO NOT EDIT.

package personnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/models"
)

// GetPersonnelOKCode is the HTTP code returned for type GetPersonnelOK
const GetPersonnelOKCode int = 200

/*
GetPersonnelOK OK

swagger:response getPersonnelOK
*/
type GetPersonnelOK struct {

	/*
	  In: Body
	*/
	Payload *models.ArrayOfPersonSummaryDTO `json:"body,omitempty"`
}

// NewGetPersonnelOK creates GetPersonnelOK with default headers values
func NewGetPersonnelOK() *GetPersonnelOK {

	return &GetPersonnelOK{}
}

// WithPayload adds the payload to the get personnel o k response
func (o *GetPersonnelOK) WithPayload(payload *models.ArrayOfPersonSummaryDTO) *GetPersonnelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get personnel o k response
func (o *GetPersonnelOK) SetPayload(payload *models.ArrayOfPersonSummaryDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPersonnelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPersonnelUnauthorizedCode is the HTTP code returned for type GetPersonnelUnauthorized
const GetPersonnelUnauthorizedCode int = 401

/*
GetPersonnelUnauthorized Error

swagger:response getPersonnelUnauthorized
*/
type GetPersonnelUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPersonnelUnauthorized creates GetPersonnelUnauthorized with default headers values
func NewGetPersonnelUnauthorized() *GetPersonnelUnauthorized {

	return &GetPersonnelUnauthorized{}
}

// WithPayload adds the payload to the get personnel unauthorized response
func (o *GetPersonnelUnauthorized) WithPayload(payload *models.Error) *GetPersonnelUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get personnel unauthorized response
func (o *GetPersonnelUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPersonnelUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPersonnelInternalServerErrorCode is the HTTP code returned for type GetPersonnelInternalServerError
const GetPersonnelInternalServerErrorCode int = 500

/*
GetPersonnelInternalServerError Error

swagger:response getPersonnelInternalServerError
*/
type GetPersonnelInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPersonnelInternalServerError creates GetPersonnelInternalServerError with default headers values
func NewGetPersonnelInternalServerError() *GetPersonnelInternalServerError {

	return &GetPersonnelInternalServerError{}
}

// WithPayload adds the payload to the get personnel internal server error response
func (o *GetPersonnelInternalServerError) WithPayload(payload *models.Error) *GetPersonnelInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get personnel internal server error response
func (o *GetPersonnelInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPersonnelInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
