// Code generated by go-swagger; DO NOT EDIT.

package personnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// GetPersonnelPeoplePersonIDOKCode is the HTTP code returned for type GetPersonnelPeoplePersonIDOK
const GetPersonnelPeoplePersonIDOKCode int = 200

/*
GetPersonnelPeoplePersonIDOK OK

swagger:response getPersonnelPeoplePersonIdOK
*/
type GetPersonnelPeoplePersonIDOK struct {

	/*
	  In: Body
	*/
	Payload *dtos.PersonDTO `json:"body,omitempty"`
}

// NewGetPersonnelPeoplePersonIDOK creates GetPersonnelPeoplePersonIDOK with default headers values
func NewGetPersonnelPeoplePersonIDOK() *GetPersonnelPeoplePersonIDOK {

	return &GetPersonnelPeoplePersonIDOK{}
}

// WithPayload adds the payload to the get personnel people person Id o k response
func (o *GetPersonnelPeoplePersonIDOK) WithPayload(payload *dtos.PersonDTO) *GetPersonnelPeoplePersonIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get personnel people person Id o k response
func (o *GetPersonnelPeoplePersonIDOK) SetPayload(payload *dtos.PersonDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPersonnelPeoplePersonIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPersonnelPeoplePersonIDUnauthorizedCode is the HTTP code returned for type GetPersonnelPeoplePersonIDUnauthorized
const GetPersonnelPeoplePersonIDUnauthorizedCode int = 401

/*
GetPersonnelPeoplePersonIDUnauthorized Error

swagger:response getPersonnelPeoplePersonIdUnauthorized
*/
type GetPersonnelPeoplePersonIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewGetPersonnelPeoplePersonIDUnauthorized creates GetPersonnelPeoplePersonIDUnauthorized with default headers values
func NewGetPersonnelPeoplePersonIDUnauthorized() *GetPersonnelPeoplePersonIDUnauthorized {

	return &GetPersonnelPeoplePersonIDUnauthorized{}
}

// WithPayload adds the payload to the get personnel people person Id unauthorized response
func (o *GetPersonnelPeoplePersonIDUnauthorized) WithPayload(payload *dtos.Error) *GetPersonnelPeoplePersonIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get personnel people person Id unauthorized response
func (o *GetPersonnelPeoplePersonIDUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPersonnelPeoplePersonIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPersonnelPeoplePersonIDInternalServerErrorCode is the HTTP code returned for type GetPersonnelPeoplePersonIDInternalServerError
const GetPersonnelPeoplePersonIDInternalServerErrorCode int = 500

/*
GetPersonnelPeoplePersonIDInternalServerError Internal server error

swagger:response getPersonnelPeoplePersonIdInternalServerError
*/
type GetPersonnelPeoplePersonIDInternalServerError struct {
}

// NewGetPersonnelPeoplePersonIDInternalServerError creates GetPersonnelPeoplePersonIDInternalServerError with default headers values
func NewGetPersonnelPeoplePersonIDInternalServerError() *GetPersonnelPeoplePersonIDInternalServerError {

	return &GetPersonnelPeoplePersonIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetPersonnelPeoplePersonIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
