// Code generated by go-swagger; DO NOT EDIT.

package personnel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// PostPersonnelPeoplePersonIDImpersonateOKCode is the HTTP code returned for type PostPersonnelPeoplePersonIDImpersonateOK
const PostPersonnelPeoplePersonIDImpersonateOKCode int = 200

/*
PostPersonnelPeoplePersonIDImpersonateOK OK

swagger:response postPersonnelPeoplePersonIdImpersonateOK
*/
type PostPersonnelPeoplePersonIDImpersonateOK struct {
}

// NewPostPersonnelPeoplePersonIDImpersonateOK creates PostPersonnelPeoplePersonIDImpersonateOK with default headers values
func NewPostPersonnelPeoplePersonIDImpersonateOK() *PostPersonnelPeoplePersonIDImpersonateOK {

	return &PostPersonnelPeoplePersonIDImpersonateOK{}
}

// WriteResponse to the client
func (o *PostPersonnelPeoplePersonIDImpersonateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostPersonnelPeoplePersonIDImpersonateUnauthorizedCode is the HTTP code returned for type PostPersonnelPeoplePersonIDImpersonateUnauthorized
const PostPersonnelPeoplePersonIDImpersonateUnauthorizedCode int = 401

/*
PostPersonnelPeoplePersonIDImpersonateUnauthorized Error

swagger:response postPersonnelPeoplePersonIdImpersonateUnauthorized
*/
type PostPersonnelPeoplePersonIDImpersonateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostPersonnelPeoplePersonIDImpersonateUnauthorized creates PostPersonnelPeoplePersonIDImpersonateUnauthorized with default headers values
func NewPostPersonnelPeoplePersonIDImpersonateUnauthorized() *PostPersonnelPeoplePersonIDImpersonateUnauthorized {

	return &PostPersonnelPeoplePersonIDImpersonateUnauthorized{}
}

// WithPayload adds the payload to the post personnel people person Id impersonate unauthorized response
func (o *PostPersonnelPeoplePersonIDImpersonateUnauthorized) WithPayload(payload *dtos.Error) *PostPersonnelPeoplePersonIDImpersonateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post personnel people person Id impersonate unauthorized response
func (o *PostPersonnelPeoplePersonIDImpersonateUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPersonnelPeoplePersonIDImpersonateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPersonnelPeoplePersonIDImpersonateInternalServerErrorCode is the HTTP code returned for type PostPersonnelPeoplePersonIDImpersonateInternalServerError
const PostPersonnelPeoplePersonIDImpersonateInternalServerErrorCode int = 500

/*
PostPersonnelPeoplePersonIDImpersonateInternalServerError Internal server error

swagger:response postPersonnelPeoplePersonIdImpersonateInternalServerError
*/
type PostPersonnelPeoplePersonIDImpersonateInternalServerError struct {
}

// NewPostPersonnelPeoplePersonIDImpersonateInternalServerError creates PostPersonnelPeoplePersonIDImpersonateInternalServerError with default headers values
func NewPostPersonnelPeoplePersonIDImpersonateInternalServerError() *PostPersonnelPeoplePersonIDImpersonateInternalServerError {

	return &PostPersonnelPeoplePersonIDImpersonateInternalServerError{}
}

// WriteResponse to the client
func (o *PostPersonnelPeoplePersonIDImpersonateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
