// Code generated by go-swagger; DO NOT EDIT.

package rostering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetShowsShowSlugSummaryHandlerFunc turns a function with the right signature into a get shows show slug summary handler
type GetShowsShowSlugSummaryHandlerFunc func(GetShowsShowSlugSummaryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetShowsShowSlugSummaryHandlerFunc) Handle(params GetShowsShowSlugSummaryParams) middleware.Responder {
	return fn(params)
}

// GetShowsShowSlugSummaryHandler interface for that can handle valid get shows show slug summary params
type GetShowsShowSlugSummaryHandler interface {
	Handle(GetShowsShowSlugSummaryParams) middleware.Responder
}

// NewGetShowsShowSlugSummary creates a new http.Handler for the get shows show slug summary operation
func NewGetShowsShowSlugSummary(ctx *middleware.Context, handler GetShowsShowSlugSummaryHandler) *GetShowsShowSlugSummary {
	return &GetShowsShowSlugSummary{Context: ctx, Handler: handler}
}

/*
	GetShowsShowSlugSummary swagger:route GET /shows/{showSlug}/summary shows getShowsShowSlugSummary

Return details about a show from its slug
*/
type GetShowsShowSlugSummary struct {
	Context *middleware.Context
	Handler GetShowsShowSlugSummaryHandler
}

func (o *GetShowsShowSlugSummary) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetShowsShowSlugSummaryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
