// Code generated by go-swagger; DO NOT EDIT.

package rostering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// PostInvitationsOKCode is the HTTP code returned for type PostInvitationsOK
const PostInvitationsOKCode int = 200

/*
PostInvitationsOK OK

swagger:response postInvitationsOK
*/
type PostInvitationsOK struct {
}

// NewPostInvitationsOK creates PostInvitationsOK with default headers values
func NewPostInvitationsOK() *PostInvitationsOK {

	return &PostInvitationsOK{}
}

// WriteResponse to the client
func (o *PostInvitationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostInvitationsBadRequestCode is the HTTP code returned for type PostInvitationsBadRequest
const PostInvitationsBadRequestCode int = 400

/*
PostInvitationsBadRequest Error

swagger:response postInvitationsBadRequest
*/
type PostInvitationsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostInvitationsBadRequest creates PostInvitationsBadRequest with default headers values
func NewPostInvitationsBadRequest() *PostInvitationsBadRequest {

	return &PostInvitationsBadRequest{}
}

// WithPayload adds the payload to the post invitations bad request response
func (o *PostInvitationsBadRequest) WithPayload(payload *dtos.Error) *PostInvitationsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invitations bad request response
func (o *PostInvitationsBadRequest) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInvitationsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInvitationsUnauthorizedCode is the HTTP code returned for type PostInvitationsUnauthorized
const PostInvitationsUnauthorizedCode int = 401

/*
PostInvitationsUnauthorized Error

swagger:response postInvitationsUnauthorized
*/
type PostInvitationsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostInvitationsUnauthorized creates PostInvitationsUnauthorized with default headers values
func NewPostInvitationsUnauthorized() *PostInvitationsUnauthorized {

	return &PostInvitationsUnauthorized{}
}

// WithPayload adds the payload to the post invitations unauthorized response
func (o *PostInvitationsUnauthorized) WithPayload(payload *dtos.Error) *PostInvitationsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invitations unauthorized response
func (o *PostInvitationsUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInvitationsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInvitationsInternalServerErrorCode is the HTTP code returned for type PostInvitationsInternalServerError
const PostInvitationsInternalServerErrorCode int = 500

/*
PostInvitationsInternalServerError Error

swagger:response postInvitationsInternalServerError
*/
type PostInvitationsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostInvitationsInternalServerError creates PostInvitationsInternalServerError with default headers values
func NewPostInvitationsInternalServerError() *PostInvitationsInternalServerError {

	return &PostInvitationsInternalServerError{}
}

// WithPayload adds the payload to the post invitations internal server error response
func (o *PostInvitationsInternalServerError) WithPayload(payload *dtos.Error) *PostInvitationsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invitations internal server error response
func (o *PostInvitationsInternalServerError) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInvitationsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
