// Code generated by go-swagger; DO NOT EDIT.

package rostering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// PostShowsShowIDUnassignOKCode is the HTTP code returned for type PostShowsShowIDUnassignOK
const PostShowsShowIDUnassignOKCode int = 200

/*
PostShowsShowIDUnassignOK OK

swagger:response postShowsShowIdUnassignOK
*/
type PostShowsShowIDUnassignOK struct {
}

// NewPostShowsShowIDUnassignOK creates PostShowsShowIDUnassignOK with default headers values
func NewPostShowsShowIDUnassignOK() *PostShowsShowIDUnassignOK {

	return &PostShowsShowIDUnassignOK{}
}

// WriteResponse to the client
func (o *PostShowsShowIDUnassignOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostShowsShowIDUnassignUnauthorizedCode is the HTTP code returned for type PostShowsShowIDUnassignUnauthorized
const PostShowsShowIDUnassignUnauthorizedCode int = 401

/*
PostShowsShowIDUnassignUnauthorized Error

swagger:response postShowsShowIdUnassignUnauthorized
*/
type PostShowsShowIDUnassignUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostShowsShowIDUnassignUnauthorized creates PostShowsShowIDUnassignUnauthorized with default headers values
func NewPostShowsShowIDUnassignUnauthorized() *PostShowsShowIDUnassignUnauthorized {

	return &PostShowsShowIDUnassignUnauthorized{}
}

// WithPayload adds the payload to the post shows show Id unassign unauthorized response
func (o *PostShowsShowIDUnassignUnauthorized) WithPayload(payload *dtos.Error) *PostShowsShowIDUnassignUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post shows show Id unassign unauthorized response
func (o *PostShowsShowIDUnassignUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShowsShowIDUnassignUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostShowsShowIDUnassignInternalServerErrorCode is the HTTP code returned for type PostShowsShowIDUnassignInternalServerError
const PostShowsShowIDUnassignInternalServerErrorCode int = 500

/*
PostShowsShowIDUnassignInternalServerError Error

swagger:response postShowsShowIdUnassignInternalServerError
*/
type PostShowsShowIDUnassignInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostShowsShowIDUnassignInternalServerError creates PostShowsShowIDUnassignInternalServerError with default headers values
func NewPostShowsShowIDUnassignInternalServerError() *PostShowsShowIDUnassignInternalServerError {

	return &PostShowsShowIDUnassignInternalServerError{}
}

// WithPayload adds the payload to the post shows show Id unassign internal server error response
func (o *PostShowsShowIDUnassignInternalServerError) WithPayload(payload *dtos.Error) *PostShowsShowIDUnassignInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post shows show Id unassign internal server error response
func (o *PostShowsShowIDUnassignInternalServerError) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShowsShowIDUnassignInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
