// Code generated by go-swagger; DO NOT EDIT.

package rostering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostShowsShowIDRosterReleaseHandlerFunc turns a function with the right signature into a post shows show ID roster release handler
type PostShowsShowIDRosterReleaseHandlerFunc func(PostShowsShowIDRosterReleaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostShowsShowIDRosterReleaseHandlerFunc) Handle(params PostShowsShowIDRosterReleaseParams) middleware.Responder {
	return fn(params)
}

// PostShowsShowIDRosterReleaseHandler interface for that can handle valid post shows show ID roster release params
type PostShowsShowIDRosterReleaseHandler interface {
	Handle(PostShowsShowIDRosterReleaseParams) middleware.Responder
}

// NewPostShowsShowIDRosterRelease creates a new http.Handler for the post shows show ID roster release operation
func NewPostShowsShowIDRosterRelease(ctx *middleware.Context, handler PostShowsShowIDRosterReleaseHandler) *PostShowsShowIDRosterRelease {
	return &PostShowsShowIDRosterRelease{Context: ctx, Handler: handler}
}

/*
	PostShowsShowIDRosterRelease swagger:route POST /shows/{showId}/roster/release rostering postShowsShowIdRosterRelease

Make the roster viewable by other members of the show
*/
type PostShowsShowIDRosterRelease struct {
	Context *middleware.Context
	Handler PostShowsShowIDRosterReleaseHandler
}

func (o *PostShowsShowIDRosterRelease) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostShowsShowIDRosterReleaseParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
