// Code generated by go-swagger; DO NOT EDIT.

package rostering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// PostInvitationsIDNotifyOKCode is the HTTP code returned for type PostInvitationsIDNotifyOK
const PostInvitationsIDNotifyOKCode int = 200

/*
PostInvitationsIDNotifyOK OK

swagger:response postInvitationsIdNotifyOK
*/
type PostInvitationsIDNotifyOK struct {
}

// NewPostInvitationsIDNotifyOK creates PostInvitationsIDNotifyOK with default headers values
func NewPostInvitationsIDNotifyOK() *PostInvitationsIDNotifyOK {

	return &PostInvitationsIDNotifyOK{}
}

// WriteResponse to the client
func (o *PostInvitationsIDNotifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostInvitationsIDNotifyUnauthorizedCode is the HTTP code returned for type PostInvitationsIDNotifyUnauthorized
const PostInvitationsIDNotifyUnauthorizedCode int = 401

/*
PostInvitationsIDNotifyUnauthorized Error

swagger:response postInvitationsIdNotifyUnauthorized
*/
type PostInvitationsIDNotifyUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostInvitationsIDNotifyUnauthorized creates PostInvitationsIDNotifyUnauthorized with default headers values
func NewPostInvitationsIDNotifyUnauthorized() *PostInvitationsIDNotifyUnauthorized {

	return &PostInvitationsIDNotifyUnauthorized{}
}

// WithPayload adds the payload to the post invitations Id notify unauthorized response
func (o *PostInvitationsIDNotifyUnauthorized) WithPayload(payload *dtos.Error) *PostInvitationsIDNotifyUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invitations Id notify unauthorized response
func (o *PostInvitationsIDNotifyUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInvitationsIDNotifyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInvitationsIDNotifyInternalServerErrorCode is the HTTP code returned for type PostInvitationsIDNotifyInternalServerError
const PostInvitationsIDNotifyInternalServerErrorCode int = 500

/*
PostInvitationsIDNotifyInternalServerError Error

swagger:response postInvitationsIdNotifyInternalServerError
*/
type PostInvitationsIDNotifyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostInvitationsIDNotifyInternalServerError creates PostInvitationsIDNotifyInternalServerError with default headers values
func NewPostInvitationsIDNotifyInternalServerError() *PostInvitationsIDNotifyInternalServerError {

	return &PostInvitationsIDNotifyInternalServerError{}
}

// WithPayload adds the payload to the post invitations Id notify internal server error response
func (o *PostInvitationsIDNotifyInternalServerError) WithPayload(payload *dtos.Error) *PostInvitationsIDNotifyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invitations Id notify internal server error response
func (o *PostInvitationsIDNotifyInternalServerError) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInvitationsIDNotifyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
