// Code generated by go-swagger; DO NOT EDIT.

package rostering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// PostInvitationsIDAcceptOKCode is the HTTP code returned for type PostInvitationsIDAcceptOK
const PostInvitationsIDAcceptOKCode int = 200

/*
PostInvitationsIDAcceptOK OK

swagger:response postInvitationsIdAcceptOK
*/
type PostInvitationsIDAcceptOK struct {
}

// NewPostInvitationsIDAcceptOK creates PostInvitationsIDAcceptOK with default headers values
func NewPostInvitationsIDAcceptOK() *PostInvitationsIDAcceptOK {

	return &PostInvitationsIDAcceptOK{}
}

// WriteResponse to the client
func (o *PostInvitationsIDAcceptOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostInvitationsIDAcceptUnauthorizedCode is the HTTP code returned for type PostInvitationsIDAcceptUnauthorized
const PostInvitationsIDAcceptUnauthorizedCode int = 401

/*
PostInvitationsIDAcceptUnauthorized Error

swagger:response postInvitationsIdAcceptUnauthorized
*/
type PostInvitationsIDAcceptUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostInvitationsIDAcceptUnauthorized creates PostInvitationsIDAcceptUnauthorized with default headers values
func NewPostInvitationsIDAcceptUnauthorized() *PostInvitationsIDAcceptUnauthorized {

	return &PostInvitationsIDAcceptUnauthorized{}
}

// WithPayload adds the payload to the post invitations Id accept unauthorized response
func (o *PostInvitationsIDAcceptUnauthorized) WithPayload(payload *dtos.Error) *PostInvitationsIDAcceptUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invitations Id accept unauthorized response
func (o *PostInvitationsIDAcceptUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInvitationsIDAcceptUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInvitationsIDAcceptInternalServerErrorCode is the HTTP code returned for type PostInvitationsIDAcceptInternalServerError
const PostInvitationsIDAcceptInternalServerErrorCode int = 500

/*
PostInvitationsIDAcceptInternalServerError Error

swagger:response postInvitationsIdAcceptInternalServerError
*/
type PostInvitationsIDAcceptInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewPostInvitationsIDAcceptInternalServerError creates PostInvitationsIDAcceptInternalServerError with default headers values
func NewPostInvitationsIDAcceptInternalServerError() *PostInvitationsIDAcceptInternalServerError {

	return &PostInvitationsIDAcceptInternalServerError{}
}

// WithPayload adds the payload to the post invitations Id accept internal server error response
func (o *PostInvitationsIDAcceptInternalServerError) WithPayload(payload *dtos.Error) *PostInvitationsIDAcceptInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invitations Id accept internal server error response
func (o *PostInvitationsIDAcceptInternalServerError) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInvitationsIDAcceptInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
