// Code generated by go-swagger; DO NOT EDIT.

package rostering

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"showplanner.io/pkg/restapi/dtos"
)

// NewPostRosteringShowsParams creates a new PostRosteringShowsParams object
//
// There are no default values defined in the spec.
func NewPostRosteringShowsParams() PostRosteringShowsParams {

	return PostRosteringShowsParams{}
}

// PostRosteringShowsParams contains all the bound params for the post rostering shows operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostRosteringShows
type PostRosteringShowsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The show to create
	  In: body
	*/
	Show *dtos.CreateShowDTO
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostRosteringShowsParams() beforehand.
func (o *PostRosteringShowsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body dtos.CreateShowDTO
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("show", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Show = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
