// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// DeleteAssignmentIDOKCode is the HTTP code returned for type DeleteAssignmentIDOK
const DeleteAssignmentIDOKCode int = 200

/*
DeleteAssignmentIDOK OK

swagger:response deleteAssignmentIdOK
*/
type DeleteAssignmentIDOK struct {
}

// NewDeleteAssignmentIDOK creates DeleteAssignmentIDOK with default headers values
func NewDeleteAssignmentIDOK() *DeleteAssignmentIDOK {

	return &DeleteAssignmentIDOK{}
}

// WriteResponse to the client
func (o *DeleteAssignmentIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteAssignmentIDUnauthorizedCode is the HTTP code returned for type DeleteAssignmentIDUnauthorized
const DeleteAssignmentIDUnauthorizedCode int = 401

/*
DeleteAssignmentIDUnauthorized Error

swagger:response deleteAssignmentIdUnauthorized
*/
type DeleteAssignmentIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewDeleteAssignmentIDUnauthorized creates DeleteAssignmentIDUnauthorized with default headers values
func NewDeleteAssignmentIDUnauthorized() *DeleteAssignmentIDUnauthorized {

	return &DeleteAssignmentIDUnauthorized{}
}

// WithPayload adds the payload to the delete assignment Id unauthorized response
func (o *DeleteAssignmentIDUnauthorized) WithPayload(payload *dtos.Error) *DeleteAssignmentIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete assignment Id unauthorized response
func (o *DeleteAssignmentIDUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAssignmentIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAssignmentIDNotFoundCode is the HTTP code returned for type DeleteAssignmentIDNotFound
const DeleteAssignmentIDNotFoundCode int = 404

/*
DeleteAssignmentIDNotFound Error

swagger:response deleteAssignmentIdNotFound
*/
type DeleteAssignmentIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewDeleteAssignmentIDNotFound creates DeleteAssignmentIDNotFound with default headers values
func NewDeleteAssignmentIDNotFound() *DeleteAssignmentIDNotFound {

	return &DeleteAssignmentIDNotFound{}
}

// WithPayload adds the payload to the delete assignment Id not found response
func (o *DeleteAssignmentIDNotFound) WithPayload(payload *dtos.Error) *DeleteAssignmentIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete assignment Id not found response
func (o *DeleteAssignmentIDNotFound) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAssignmentIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAssignmentIDInternalServerErrorCode is the HTTP code returned for type DeleteAssignmentIDInternalServerError
const DeleteAssignmentIDInternalServerErrorCode int = 500

/*
DeleteAssignmentIDInternalServerError Error

swagger:response deleteAssignmentIdInternalServerError
*/
type DeleteAssignmentIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewDeleteAssignmentIDInternalServerError creates DeleteAssignmentIDInternalServerError with default headers values
func NewDeleteAssignmentIDInternalServerError() *DeleteAssignmentIDInternalServerError {

	return &DeleteAssignmentIDInternalServerError{}
}

// WithPayload adds the payload to the delete assignment Id internal server error response
func (o *DeleteAssignmentIDInternalServerError) WithPayload(payload *dtos.Error) *DeleteAssignmentIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete assignment Id internal server error response
func (o *DeleteAssignmentIDInternalServerError) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAssignmentIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
