// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// GetRosterOKCode is the HTTP code returned for type GetRosterOK
const GetRosterOKCode int = 200

/*
GetRosterOK OK

swagger:response getRosterOK
*/
type GetRosterOK struct {

	/*
	  In: Body
	*/
	Payload *dtos.RosterDTO `json:"body,omitempty"`
}

// NewGetRosterOK creates GetRosterOK with default headers values
func NewGetRosterOK() *GetRosterOK {

	return &GetRosterOK{}
}

// WithPayload adds the payload to the get roster o k response
func (o *GetRosterOK) WithPayload(payload *dtos.RosterDTO) *GetRosterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get roster o k response
func (o *GetRosterOK) SetPayload(payload *dtos.RosterDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRosterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRosterUnauthorizedCode is the HTTP code returned for type GetRosterUnauthorized
const GetRosterUnauthorizedCode int = 401

/*
GetRosterUnauthorized Error

swagger:response getRosterUnauthorized
*/
type GetRosterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewGetRosterUnauthorized creates GetRosterUnauthorized with default headers values
func NewGetRosterUnauthorized() *GetRosterUnauthorized {

	return &GetRosterUnauthorized{}
}

// WithPayload adds the payload to the get roster unauthorized response
func (o *GetRosterUnauthorized) WithPayload(payload *dtos.Error) *GetRosterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get roster unauthorized response
func (o *GetRosterUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRosterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRosterInternalServerErrorCode is the HTTP code returned for type GetRosterInternalServerError
const GetRosterInternalServerErrorCode int = 500

/*
GetRosterInternalServerError Error

swagger:response getRosterInternalServerError
*/
type GetRosterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewGetRosterInternalServerError creates GetRosterInternalServerError with default headers values
func NewGetRosterInternalServerError() *GetRosterInternalServerError {

	return &GetRosterInternalServerError{}
}

// WithPayload adds the payload to the get roster internal server error response
func (o *GetRosterInternalServerError) WithPayload(payload *dtos.Error) *GetRosterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get roster internal server error response
func (o *GetRosterInternalServerError) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRosterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
