// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/models"
)

// GetMeOKCode is the HTTP code returned for type GetMeOK
const GetMeOKCode int = 200

/*
GetMeOK Details about logged in user

swagger:response getMeOK
*/
type GetMeOK struct {

	/*
	  In: Body
	*/
	Payload *models.MeDetailsDTO `json:"body,omitempty"`
}

// NewGetMeOK creates GetMeOK with default headers values
func NewGetMeOK() *GetMeOK {

	return &GetMeOK{}
}

// WithPayload adds the payload to the get me o k response
func (o *GetMeOK) WithPayload(payload *models.MeDetailsDTO) *GetMeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get me o k response
func (o *GetMeOK) SetPayload(payload *models.MeDetailsDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMeUnauthorizedCode is the HTTP code returned for type GetMeUnauthorized
const GetMeUnauthorizedCode int = 401

/*
GetMeUnauthorized Error

swagger:response getMeUnauthorized
*/
type GetMeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMeUnauthorized creates GetMeUnauthorized with default headers values
func NewGetMeUnauthorized() *GetMeUnauthorized {

	return &GetMeUnauthorized{}
}

// WithPayload adds the payload to the get me unauthorized response
func (o *GetMeUnauthorized) WithPayload(payload *models.Error) *GetMeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get me unauthorized response
func (o *GetMeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMeInternalServerErrorCode is the HTTP code returned for type GetMeInternalServerError
const GetMeInternalServerErrorCode int = 500

/*
GetMeInternalServerError Internal server error

swagger:response getMeInternalServerError
*/
type GetMeInternalServerError struct {
}

// NewGetMeInternalServerError creates GetMeInternalServerError with default headers values
func NewGetMeInternalServerError() *GetMeInternalServerError {

	return &GetMeInternalServerError{}
}

// WriteResponse to the client
func (o *GetMeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
