// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// GetPublicHealthOKCode is the HTTP code returned for type GetPublicHealthOK
const GetPublicHealthOKCode int = 200

/*
GetPublicHealthOK OK

swagger:response getPublicHealthOK
*/
type GetPublicHealthOK struct {

	/*
	  In: Body
	*/
	Payload *dtos.HealthCheck `json:"body,omitempty"`
}

// NewGetPublicHealthOK creates GetPublicHealthOK with default headers values
func NewGetPublicHealthOK() *GetPublicHealthOK {

	return &GetPublicHealthOK{}
}

// WithPayload adds the payload to the get public health o k response
func (o *GetPublicHealthOK) WithPayload(payload *dtos.HealthCheck) *GetPublicHealthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get public health o k response
func (o *GetPublicHealthOK) SetPayload(payload *dtos.HealthCheck) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPublicHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
