// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetShowreportsIDPdfHandlerFunc turns a function with the right signature into a get showreports ID pdf handler
type GetShowreportsIDPdfHandlerFunc func(GetShowreportsIDPdfParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetShowreportsIDPdfHandlerFunc) Handle(params GetShowreportsIDPdfParams) middleware.Responder {
	return fn(params)
}

// GetShowreportsIDPdfHandler interface for that can handle valid get showreports ID pdf params
type GetShowreportsIDPdfHandler interface {
	Handle(GetShowreportsIDPdfParams) middleware.Responder
}

// NewGetShowreportsIDPdf creates a new http.Handler for the get showreports ID pdf operation
func NewGetShowreportsIDPdf(ctx *middleware.Context, handler GetShowreportsIDPdfHandler) *GetShowreportsIDPdf {
	return &GetShowreportsIDPdf{Context: ctx, Handler: handler}
}

/*
	GetShowreportsIDPdf swagger:route GET /showreports/{id}/pdf getShowreportsIdPdf

Returns the report in the PDF format
*/
type GetShowreportsIDPdf struct {
	Context *middleware.Context
	Handler GetShowreportsIDPdfHandler
}

func (o *GetShowreportsIDPdf) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetShowreportsIDPdfParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
