// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostShowreportIDHandlerFunc turns a function with the right signature into a post showreport ID handler
type PostShowreportIDHandlerFunc func(PostShowreportIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostShowreportIDHandlerFunc) Handle(params PostShowreportIDParams) middleware.Responder {
	return fn(params)
}

// PostShowreportIDHandler interface for that can handle valid post showreport ID params
type PostShowreportIDHandler interface {
	Handle(PostShowreportIDParams) middleware.Responder
}

// NewPostShowreportID creates a new http.Handler for the post showreport ID operation
func NewPostShowreportID(ctx *middleware.Context, handler PostShowreportIDHandler) *PostShowreportID {
	return &PostShowreportID{Context: ctx, Handler: handler}
}

/*
	PostShowreportID swagger:route POST /showreport/{id} postShowreportId

Adds a person to a show
*/
type PostShowreportID struct {
	Context *middleware.Context
	Handler PostShowreportIDHandler
}

func (o *PostShowreportID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostShowreportIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
