// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/models"
)

// PostShowreportOKCode is the HTTP code returned for type PostShowreportOK
const PostShowreportOKCode int = 200

/*
PostShowreportOK OK

swagger:response postShowreportOK
*/
type PostShowreportOK struct {
}

// NewPostShowreportOK creates PostShowreportOK with default headers values
func NewPostShowreportOK() *PostShowreportOK {

	return &PostShowreportOK{}
}

// WriteResponse to the client
func (o *PostShowreportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostShowreportUnauthorizedCode is the HTTP code returned for type PostShowreportUnauthorized
const PostShowreportUnauthorizedCode int = 401

/*
PostShowreportUnauthorized Error

swagger:response postShowreportUnauthorized
*/
type PostShowreportUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostShowreportUnauthorized creates PostShowreportUnauthorized with default headers values
func NewPostShowreportUnauthorized() *PostShowreportUnauthorized {

	return &PostShowreportUnauthorized{}
}

// WithPayload adds the payload to the post showreport unauthorized response
func (o *PostShowreportUnauthorized) WithPayload(payload *models.Error) *PostShowreportUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post showreport unauthorized response
func (o *PostShowreportUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShowreportUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostShowreportInternalServerErrorCode is the HTTP code returned for type PostShowreportInternalServerError
const PostShowreportInternalServerErrorCode int = 500

/*
PostShowreportInternalServerError Error

swagger:response postShowreportInternalServerError
*/
type PostShowreportInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostShowreportInternalServerError creates PostShowreportInternalServerError with default headers values
func NewPostShowreportInternalServerError() *PostShowreportInternalServerError {

	return &PostShowreportInternalServerError{}
}

// WithPayload adds the payload to the post showreport internal server error response
func (o *PostShowreportInternalServerError) WithPayload(payload *models.Error) *PostShowreportInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post showreport internal server error response
func (o *PostShowreportInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShowreportInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
