// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostImpersonateHandlerFunc turns a function with the right signature into a post impersonate handler
type PostImpersonateHandlerFunc func(PostImpersonateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostImpersonateHandlerFunc) Handle(params PostImpersonateParams) middleware.Responder {
	return fn(params)
}

// PostImpersonateHandler interface for that can handle valid post impersonate params
type PostImpersonateHandler interface {
	Handle(PostImpersonateParams) middleware.Responder
}

// NewPostImpersonate creates a new http.Handler for the post impersonate operation
func NewPostImpersonate(ctx *middleware.Context, handler PostImpersonateHandler) *PostImpersonate {
	return &PostImpersonate{Context: ctx, Handler: handler}
}

/*
	PostImpersonate swagger:route POST /impersonate postImpersonate

PostImpersonate post impersonate API
*/
type PostImpersonate struct {
	Context *middleware.Context
	Handler PostImpersonateHandler
}

func (o *PostImpersonate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostImpersonateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
