// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/models"
)

// PostShowreportIDOKCode is the HTTP code returned for type PostShowreportIDOK
const PostShowreportIDOKCode int = 200

/*
PostShowreportIDOK OK

swagger:response postShowreportIdOK
*/
type PostShowreportIDOK struct {
}

// NewPostShowreportIDOK creates PostShowreportIDOK with default headers values
func NewPostShowreportIDOK() *PostShowreportIDOK {

	return &PostShowreportIDOK{}
}

// WriteResponse to the client
func (o *PostShowreportIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostShowreportIDUnauthorizedCode is the HTTP code returned for type PostShowreportIDUnauthorized
const PostShowreportIDUnauthorizedCode int = 401

/*
PostShowreportIDUnauthorized Error

swagger:response postShowreportIdUnauthorized
*/
type PostShowreportIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostShowreportIDUnauthorized creates PostShowreportIDUnauthorized with default headers values
func NewPostShowreportIDUnauthorized() *PostShowreportIDUnauthorized {

	return &PostShowreportIDUnauthorized{}
}

// WithPayload adds the payload to the post showreport Id unauthorized response
func (o *PostShowreportIDUnauthorized) WithPayload(payload *models.Error) *PostShowreportIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post showreport Id unauthorized response
func (o *PostShowreportIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShowreportIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostShowreportIDInternalServerErrorCode is the HTTP code returned for type PostShowreportIDInternalServerError
const PostShowreportIDInternalServerErrorCode int = 500

/*
PostShowreportIDInternalServerError Error

swagger:response postShowreportIdInternalServerError
*/
type PostShowreportIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostShowreportIDInternalServerError creates PostShowreportIDInternalServerError with default headers values
func NewPostShowreportIDInternalServerError() *PostShowreportIDInternalServerError {

	return &PostShowreportIDInternalServerError{}
}

// WithPayload adds the payload to the post showreport Id internal server error response
func (o *PostShowreportIDInternalServerError) WithPayload(payload *models.Error) *PostShowreportIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post showreport Id internal server error response
func (o *PostShowreportIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShowreportIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
