// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAvailabilitiesHandlerFunc turns a function with the right signature into a post availabilities handler
type PostAvailabilitiesHandlerFunc func(PostAvailabilitiesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAvailabilitiesHandlerFunc) Handle(params PostAvailabilitiesParams) middleware.Responder {
	return fn(params)
}

// PostAvailabilitiesHandler interface for that can handle valid post availabilities params
type PostAvailabilitiesHandler interface {
	Handle(PostAvailabilitiesParams) middleware.Responder
}

// NewPostAvailabilities creates a new http.Handler for the post availabilities operation
func NewPostAvailabilities(ctx *middleware.Context, handler PostAvailabilitiesHandler) *PostAvailabilities {
	return &PostAvailabilities{Context: ctx, Handler: handler}
}

/*
	PostAvailabilities swagger:route POST /availabilities postAvailabilities

Create or update availability
*/
type PostAvailabilities struct {
	Context *middleware.Context
	Handler PostAvailabilitiesHandler
}

func (o *PostAvailabilities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAvailabilitiesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
