// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetPublicScheduleParams creates a new GetPublicScheduleParams object
//
// There are no default values defined in the spec.
func NewGetPublicScheduleParams() GetPublicScheduleParams {

	return GetPublicScheduleParams{}
}

// GetPublicScheduleParams contains all the bound params for the get public schedule operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetPublicSchedule
type GetPublicScheduleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of the show to get events from
	  Required: true
	  In: query
	*/
	ShowSlug string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPublicScheduleParams() beforehand.
func (o *GetPublicScheduleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qShowSlug, qhkShowSlug, _ := qs.GetOK("showSlug")
	if err := o.bindShowSlug(qShowSlug, qhkShowSlug, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindShowSlug binds and validates parameter ShowSlug from query.
func (o *GetPublicScheduleParams) bindShowSlug(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("showSlug", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("showSlug", "query", raw); err != nil {
		return err
	}
	o.ShowSlug = raw

	return nil
}
