// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPublicHealthHandlerFunc turns a function with the right signature into a get public health handler
type GetPublicHealthHandlerFunc func(GetPublicHealthParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPublicHealthHandlerFunc) Handle(params GetPublicHealthParams) middleware.Responder {
	return fn(params)
}

// GetPublicHealthHandler interface for that can handle valid get public health params
type GetPublicHealthHandler interface {
	Handle(GetPublicHealthParams) middleware.Responder
}

// NewGetPublicHealth creates a new http.Handler for the get public health operation
func NewGetPublicHealth(ctx *middleware.Context, handler GetPublicHealthHandler) *GetPublicHealth {
	return &GetPublicHealth{Context: ctx, Handler: handler}
}

/*
	GetPublicHealth swagger:route GET /public/health getPublicHealth

# Healthcheck

Healthcheck endpoint
*/
type GetPublicHealth struct {
	Context *middleware.Context
	Handler GetPublicHealthHandler
}

func (o *GetPublicHealth) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPublicHealthParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
