// Code generated by go-swagger; DO NOT EDIT.

package showdocs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"showplanner.io/pkg/restapi/dtos"
)

// GetShowdocTimersIDOKCode is the HTTP code returned for type GetShowdocTimersIDOK
const GetShowdocTimersIDOKCode int = 200

/*
GetShowdocTimersIDOK OK

swagger:response getShowdocTimersIdOK
*/
type GetShowdocTimersIDOK struct {

	/*
	  In: Body
	*/
	Payload *dtos.ShowTimerDTO `json:"body,omitempty"`
}

// NewGetShowdocTimersIDOK creates GetShowdocTimersIDOK with default headers values
func NewGetShowdocTimersIDOK() *GetShowdocTimersIDOK {

	return &GetShowdocTimersIDOK{}
}

// WithPayload adds the payload to the get showdoc timers Id o k response
func (o *GetShowdocTimersIDOK) WithPayload(payload *dtos.ShowTimerDTO) *GetShowdocTimersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get showdoc timers Id o k response
func (o *GetShowdocTimersIDOK) SetPayload(payload *dtos.ShowTimerDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShowdocTimersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetShowdocTimersIDUnauthorizedCode is the HTTP code returned for type GetShowdocTimersIDUnauthorized
const GetShowdocTimersIDUnauthorizedCode int = 401

/*
GetShowdocTimersIDUnauthorized Error

swagger:response getShowdocTimersIdUnauthorized
*/
type GetShowdocTimersIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewGetShowdocTimersIDUnauthorized creates GetShowdocTimersIDUnauthorized with default headers values
func NewGetShowdocTimersIDUnauthorized() *GetShowdocTimersIDUnauthorized {

	return &GetShowdocTimersIDUnauthorized{}
}

// WithPayload adds the payload to the get showdoc timers Id unauthorized response
func (o *GetShowdocTimersIDUnauthorized) WithPayload(payload *dtos.Error) *GetShowdocTimersIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get showdoc timers Id unauthorized response
func (o *GetShowdocTimersIDUnauthorized) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShowdocTimersIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetShowdocTimersIDNotFoundCode is the HTTP code returned for type GetShowdocTimersIDNotFound
const GetShowdocTimersIDNotFoundCode int = 404

/*
GetShowdocTimersIDNotFound Error

swagger:response getShowdocTimersIdNotFound
*/
type GetShowdocTimersIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewGetShowdocTimersIDNotFound creates GetShowdocTimersIDNotFound with default headers values
func NewGetShowdocTimersIDNotFound() *GetShowdocTimersIDNotFound {

	return &GetShowdocTimersIDNotFound{}
}

// WithPayload adds the payload to the get showdoc timers Id not found response
func (o *GetShowdocTimersIDNotFound) WithPayload(payload *dtos.Error) *GetShowdocTimersIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get showdoc timers Id not found response
func (o *GetShowdocTimersIDNotFound) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShowdocTimersIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetShowdocTimersIDInternalServerErrorCode is the HTTP code returned for type GetShowdocTimersIDInternalServerError
const GetShowdocTimersIDInternalServerErrorCode int = 500

/*
GetShowdocTimersIDInternalServerError Error

swagger:response getShowdocTimersIdInternalServerError
*/
type GetShowdocTimersIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *dtos.Error `json:"body,omitempty"`
}

// NewGetShowdocTimersIDInternalServerError creates GetShowdocTimersIDInternalServerError with default headers values
func NewGetShowdocTimersIDInternalServerError() *GetShowdocTimersIDInternalServerError {

	return &GetShowdocTimersIDInternalServerError{}
}

// WithPayload adds the payload to the get showdoc timers Id internal server error response
func (o *GetShowdocTimersIDInternalServerError) WithPayload(payload *dtos.Error) *GetShowdocTimersIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get showdoc timers Id internal server error response
func (o *GetShowdocTimersIDInternalServerError) SetPayload(payload *dtos.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetShowdocTimersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
