// Code generated by go-swagger; DO NOT EDIT.

package showdocs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetShowdocTimersIDHandlerFunc turns a function with the right signature into a get showdoc timers ID handler
type GetShowdocTimersIDHandlerFunc func(GetShowdocTimersIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetShowdocTimersIDHandlerFunc) Handle(params GetShowdocTimersIDParams) middleware.Responder {
	return fn(params)
}

// GetShowdocTimersIDHandler interface for that can handle valid get showdoc timers ID params
type GetShowdocTimersIDHandler interface {
	Handle(GetShowdocTimersIDParams) middleware.Responder
}

// NewGetShowdocTimersID creates a new http.Handler for the get showdoc timers ID operation
func NewGetShowdocTimersID(ctx *middleware.Context, handler GetShowdocTimersIDHandler) *GetShowdocTimersID {
	return &GetShowdocTimersID{Context: ctx, Handler: handler}
}

/*
	GetShowdocTimersID swagger:route GET /showdoc/timers/{id} showdocs getShowdocTimersId

Gets a particular show timer
*/
type GetShowdocTimersID struct {
	Context *middleware.Context
	Handler GetShowdocTimersIDHandler
}

func (o *GetShowdocTimersID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetShowdocTimersIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
