// Code generated by go-swagger; DO NOT EDIT.

package showdocs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetShowdocReportsHandlerFunc turns a function with the right signature into a get showdoc reports handler
type GetShowdocReportsHandlerFunc func(GetShowdocReportsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetShowdocReportsHandlerFunc) Handle(params GetShowdocReportsParams) middleware.Responder {
	return fn(params)
}

// GetShowdocReportsHandler interface for that can handle valid get showdoc reports params
type GetShowdocReportsHandler interface {
	Handle(GetShowdocReportsParams) middleware.Responder
}

// NewGetShowdocReports creates a new http.Handler for the get showdoc reports operation
func NewGetShowdocReports(ctx *middleware.Context, handler GetShowdocReportsHandler) *GetShowdocReports {
	return &GetShowdocReports{Context: ctx, Handler: handler}
}

/*
	GetShowdocReports swagger:route GET /showdoc/reports showdocs getShowdocReports

Get users show reports
*/
type GetShowdocReports struct {
	Context *middleware.Context
	Handler GetShowdocReportsHandler
}

func (o *GetShowdocReports) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetShowdocReportsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
