// Code generated by go-swagger; DO NOT EDIT.

package dtos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PersonDTOWithEmail person d t o with email
//
// swagger:model personDTOWithEmail
type PersonDTOWithEmail struct {
	PersonDTO

	// email
	Email string `json:"email,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PersonDTOWithEmail) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 PersonDTO
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.PersonDTO = aO0

	// AO1
	var dataAO1 struct {
		Email string `json:"email,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Email = dataAO1.Email

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PersonDTOWithEmail) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.PersonDTO)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Email string `json:"email,omitempty"`
	}

	dataAO1.Email = m.Email

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this person d t o with email
func (m *PersonDTOWithEmail) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with PersonDTO
	if err := m.PersonDTO.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this person d t o with email based on the context it is used
func (m *PersonDTOWithEmail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with PersonDTO
	if err := m.PersonDTO.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PersonDTOWithEmail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonDTOWithEmail) UnmarshalBinary(b []byte) error {
	var res PersonDTOWithEmail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
