// Code generated by go-swagger; DO NOT EDIT.

package dtos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// RoleSetOrderDTO ID of roles in desired order
//
// swagger:model roleSetOrderDTO
type RoleSetOrderDTO []int64

// Validate validates this role set order d t o
func (m RoleSetOrderDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this role set order d t o based on context it is used
func (m RoleSetOrderDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
