// Code generated by go-swagger; DO NOT EDIT.

package dtos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShowReportForEvent show report for event
//
// swagger:model showReportForEvent
type ShowReportForEvent struct {

	// show report
	ShowReport *ShowReportDTO `json:"showReport,omitempty"`

	// subtitle
	Subtitle string `json:"subtitle,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this show report for event
func (m *ShowReportForEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateShowReport(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShowReportForEvent) validateShowReport(formats strfmt.Registry) error {
	if swag.IsZero(m.ShowReport) { // not required
		return nil
	}

	if m.ShowReport != nil {
		if err := m.ShowReport.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("showReport")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("showReport")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this show report for event based on the context it is used
func (m *ShowReportForEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateShowReport(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShowReportForEvent) contextValidateShowReport(ctx context.Context, formats strfmt.Registry) error {

	if m.ShowReport != nil {

		if swag.IsZero(m.ShowReport) { // not required
			return nil
		}

		if err := m.ShowReport.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("showReport")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("showReport")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ShowReportForEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShowReportForEvent) UnmarshalBinary(b []byte) error {
	var res ShowReportForEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
