[context.production]
  environment = { NEXT_PUBLIC_API_URL="https://api.showplanner.io/v1", NODE_ENV = "production" }

[build]
  command = "yarn build"
  publish = ".next/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]
