// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateEventDTO create event d t o
//
// swagger:model CreateEventDTO
type CreateEventDTO struct {

	// show Id
	// Required: true
	ShowID *int64 `json:"showId"`

	// start
	// Required: true
	Start *string `json:"start"`
}

// Validate validates this create event d t o
func (m *CreateEventDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateShowID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStart(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateEventDTO) validateShowID(formats strfmt.Registry) error {

	if err := validate.Required("showId", "body", m.ShowID); err != nil {
		return err
	}

	return nil
}

func (m *CreateEventDTO) validateStart(formats strfmt.Registry) error {

	if err := validate.Required("start", "body", m.Start); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create event d t o based on context it is used
func (m *CreateEventDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateEventDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateEventDTO) UnmarshalBinary(b []byte) error {
	var res CreateEventDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
