# Use postgres/example user/password credentials
version: '3.1'

services:

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:7.0
    restart: always
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_USER: supertokens
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE_NAME: supertokens

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: supertokens
      POSTGRES_DB: supertokens
    volumes:
      - database_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3568:3568
volumes:
  database_volume:
