# Use postgres/example user/password credentials
version: '3.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
      - SERICES=s3
    volumes:
      - "localstack:/var/lib/localstack"
      - ./localstack:/etc/localstack/init/ready.d
      - "/var/run/docker.sock:/var/run/docker.sock"
  nginx:
    build: nginx-local
    depends_on:
      db:
        condition: service_healthy
    network_mode: "host"
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:7.0
    restart: always
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_USER: supertokens
      POSTGRESQL_PASSWORD: supertokens
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE_NAME: supertokens
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      SUPERTOKENS_USER: supertokens
      SUPERTOKENS_PASSWORD: supertokens
      SUPERTOKENS_DATABASE: supertokens
      SHOWPLANNER_USER: showplanner
      SHOWPLANNER_PASSWORD: showplanner
      SHOWPLANNER_DATABASE: showplanner
    volumes:
      - database_volume:/var/lib/postgresql/data
      - ./compose-multiple-databases.sh:/docker-entrypoint-initdb.d/setup.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 3568:8080

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.3.1
  #   logging:
  #     driver: none
  #   restart: unless-stopped
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181

  # kafka:
  #   image: confluentinc/cp-kafka:7.3.1
  #   logging:
  #     driver: none
  #   restart: unless-stopped
  #   ports:
  #     - 9092:9092
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
volumes:
  database_volume:
  localstack:
