#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Checking everything builds..."

yarn concurrently "(cd packages/frontend && yarn build)" "(cd packages/backend && make build)" "(cd packages/openapi && make validate)"

